"""Editted models

Revision ID: 29f5c04539c3
Revises: 9326f89afe90
Create Date: 2023-12-27 14:12:26.039794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f5c04539c3'
down_revision = '9326f89afe90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
