"""Freebies class table

Revision ID: 31785c9690e0
Revises: 5f72c58bf48c
Create Date: 2023-12-27 12:31:22.687794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31785c9690e0'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freebies')
    # ### end Alembic commands ###
