"""Tables relationships editted

Revision ID: 9326f89afe90
Revises: 9cd8e4c0fac9
Create Date: 2023-12-27 13:26:48.061328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9326f89afe90'
down_revision = '9cd8e4c0fac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
